window.BAKEHOUSE_MENU = {
    categories: [
        {
            slug: "bread",
            icon: "fa-bread-slice",
            image: "images/bread.jpg",
            name: { en: "Bread", vi: "Banh mi va banh nuong" },
            intro: { en: "Fresh loaves, rolls, croissants, doughnuts and bakery favourites for the whole day.", vi: "Banh mi, banh cuon, croissant, donut va cac mon banh moi ra lo moi ngay." },
            items: [
                ["Meringue Worm", "$4.50"], ["White High Top Unsliced", "$6.00"], ["Hot Dog Rolls", "$7.20"], ["Whole Meal Loaves", "$5.80"], ["Marshmallow Corn", "$4.50"], ["Jam Doughnuts", "$5.80"], ["Fresh Sliced White Loaves", "$5.80"], ["Plain Croissant", "$5.20"], ["Nutella Doughnuts", "$5.80"], ["White High Top Sliced", "$6.00"], ["Pack Rolls", "$6.80"], ["Scroll Vegemite", "$4.50"], ["Apple Danish", "$6.50"], ["French Stick No Seed", "$5.90"], ["Hamburger 6 Packs", "$5.80"], ["Blueberry Danish", "$6.50"], ["Hawaiian Pizza", "$5.20"], ["Ham And Cheese Croissant Toasted", "$7.90"], ["Dinner Rolls", "$5.20"], ["6 Pack Vietnamese Rolls", "$7.20"], ["Caramel Doughnuts", "$5.80"], ["Large Cob Loaves Unsliced", "$6.20"], ["Cinnamon Twist Doughnuts", "$5.20"], ["Vienna Unsliced", "$6.20"], ["Mock Cream Large Flower Buns", "$12.00"], ["Meat Lover Pizza", "$5.20"]
            ]
        },
        {
            slug: "wraps-focaccia",
            icon: "fa-utensils",
            image: "images/sandwiches.png",
            name: { en: "Wraps & Focaccia", vi: "Wrap va focaccia" },
            intro: { en: "Made-to-go lunches with fresh fillings, soft wraps and toasted focaccia.", vi: "Bua trua tien loi voi nhan tuoi, wrap mem va focaccia nuong am." },
            items: [["Chicken And Avocado Wrap", "$14.50"], ["Chicken Focaccia", "$15.60"], ["Ham And Avocado Wrap", "$14.50"], ["Ham Focaccia", "$15.60"]]
        },
        {
            slug: "banh-mi",
            icon: "fa-pepper-hot",
            image: "images/banh mi.jpeg",
            name: { en: "Vietnamese Banh Mi", vi: "Banh mi Viet Nam" },
            intro: { en: "Crispy rolls, savoury meats, pickled veg, herbs and the house sauces people come back for.", vi: "Banh mi gion, thit dam da, do chua, rau thom va sot nha lam." },
            items: [["Roasted Pork Banh Mi", "$15.60"], ["Lemongrass Chicken Banh Mi", "$14.50"], ["BBQ Pork Banh Mi", "$14.50"], ["Grilled Chicken Banh Mi", "$14.50"], ["Vietnamese Signature Banh Mi", "$15.60"], ["Grilled Pork Banh Mi", "$14.50"], ["Fried Rice", "$14.50"], ["Fried Noodles", "$14.50"]]
        },
        {
            slug: "vermicelli-salad-bowls",
            icon: "fa-bowl-food",
            image: "images/vermicelli bowl.avif",
            name: { en: "Vermicelli Salad Bowls", vi: "Bun salad" },
            intro: { en: "Fresh noodle bowls with grilled meats, salad, herbs and bright Vietnamese flavour.", vi: "To bun tuoi voi thit nuong, rau, rau thom va huong vi Viet Nam tuoi mat." },
            items: [["Grilled Pork Noodle Salad Bowl", "$17.50"], ["Lemongrass Chicken Noodle Salad Bowl", "$17.50"], ["Grilled Chicken Noodle Salad Bowl", "$17.50"], ["Combination Noodle Salad Bowl", "$17.50"]]
        },
        {
            slug: "rice-paper-rolls",
            icon: "fa-leaf",
            image: "images/rice paper.webp",
            name: { en: "Rice Paper Rolls", vi: "Goi cuon" },
            intro: { en: "Light, fresh rice paper rolls packed with protein, herbs and crisp vegetables.", vi: "Goi cuon nhe bung voi thit, rau thom va rau tuoi gion." },
            items: [["Chicken & Avocado Rice Paper Rolls", "$11.00"], ["Pork And Prawns Rice Paper Rolls", "$11.00"], ["Lemongrass Chicken Rice Paper Rolls", "$11.00"], ["BBQ Pork Rice Paper Rolls", "$11.00"], ["Grilled Chicken Rice Paper Rolls", "$11.00"], ["Grilled Pork Rice Paper Rolls", "$11.00"]]
        },
        {
            slug: "salad-rolls",
            icon: "fa-seedling",
            image: "images/pastry array.png",
            name: { en: "Salad Rolls", vi: "Banh mi salad" },
            intro: { en: "Classic salad rolls made fresh with ham or chicken.", vi: "Banh mi salad lam moi voi ham hoac ga." },
            items: [["Ham Salad Roll", "$13.00"], ["Chicken Salad Roll", "$13.00"]]
        },
        {
            slug: "sandwiches",
            icon: "fa-burger",
            image: "images/wraps.webp",
            name: { en: "Sandwiches", vi: "Sandwich" },
            intro: { en: "Simple, fresh sandwiches for an easy bakery lunch.", vi: "Sandwich tuoi ngon, don gian cho bua trua nhanh." },
            items: [["Chicken, Cheese And Lettuce Sandwich", "$9.80"], ["Eggs And Lettuce Sandwich", "$9.80"], ["Ham, Cheese And Tomato Sandwich", "$9.80"]]
        },
        {
            slug: "hot-food",
            icon: "fa-fire-flame-curved",
            image: "images/pie array.png",
            name: { en: "Hot Food", vi: "Mon nong" },
            intro: { en: "Pies, sausage rolls, quiche, spring rolls and hot bakery classics.", vi: "Pie, sausage roll, quiche, cha gio va cac mon nong quen thuoc." },
            items: [["Quiche Lorraine", "$8.50"], ["Smokey Dog", "$7.80"], ["Spinach And Feta", "$7.80"], ["Chunky Steak Pepper Pie", "$8.90"], ["Chunky Beef Curry Pie", "$8.90"], ["Mince & Veggie Pasty", "$7.80"], ["Chunky Steak Cheese Pie", "$8.90"], ["Roasted Pork Gravy Roll", "$13.00"], ["Vietnamese Pork Meatball Skewer", "$6.00"], ["Mini Quiche", "$4.50"], ["Curry Beef Minced", "$8.80"], ["Beef Minced And Cheese", "$8.80"], ["Steak, Tomato And Onion Pie", "$8.90"], ["Classic Beef Minced Pie", "$8.90"], ["Pork Spring Rolls", "$7.80"], ["Plain Sausage Roll", "$6.90"], ["Cheese Bacon Sausage Roll", "$7.50"], ["Mini Pie", "$4.50"], ["Steak, Cheese And Bacon Pie", "$8.90"], ["Potato Pie", "$9.75"], ["Quiche Vegetarian", "$8.50"], ["Plain Chunky Beef", "$8.80"], ["Chunky Steak Pie", "$8.90"], ["Curry Sausage Rolls", "$6.90"], ["Chunky Beef Bacon Pie", "$8.90"], ["Creamy Chicken And Vegetable Pie", "$8.80"], ["Chunky Beef Mushroom Pie", "$8.90"], ["Creamy Chicken Curry", "$8.80"], ["Steak Kidney Pie", "$8.90"], ["Sauce (BBQ or Tomato)", "$0.80"]]
        },
        {
            slug: "slices",
            icon: "fa-cake-candles",
            image: "images/cake array.png",
            name: { en: "Slices", vi: "Banh ngot cat mieng" },
            intro: { en: "Cheesecakes, vanilla slices, lamingtons, tarts and sweet cabinet favourites.", vi: "Cheesecake, vanilla slice, lamington, tart va nhieu mon ngot hap dan." },
            items: [["Caramel Cheesecake Slice", "$6.50"], ["Mock Cream Doughnut", "$7.00"], ["Mud Cake Slice", "$7.00"], ["Apple Slice", "$6.50"], ["Vanilla Slice", "$7.00"], ["Lemon Meringue Pie Slice", "$7.00"], ["Custard Tart Slice", "$7.00"], ["Strawberry Cheesecake Slice", "$7.00"], ["Apple Turnover Slice", "$7.80"], ["Caramel Slice", "$7.00"], ["Lamington With Cream Slice", "$7.00"], ["French Vanilla Slice", "$7.50"], ["Passion Fruit Cheesecake Slice", "$7.00"], ["Caramel Cheesecake", "$6.50"], ["Carrot Cake Slice", "$7.00"], ["Plain Lamington", "$4.50"], ["Fresh Cream Doughnut", "$7.00"]]
        },
        {
            slug: "cakes",
            icon: "fa-birthday-cake",
            image: "images/cake.jpeg",
            name: { en: "Cakes", vi: "Banh kem va banh lon" },
            intro: { en: "Family pies, sponge cakes, Swiss rolls and celebration cakes.", vi: "Pie gia dinh, sponge cake, swiss roll va banh cho dip dac biet." },
            items: [["Family Apple Pie", "$20.00"], ["Honey Swiss Roll Cake", "$14.50"], ["Carrot Cake Bar", "$16.50"], ["Apple Tea Cake", "$12.50"], ["Apple Pie", "$7.80"], ["Jam Swiss Roll Cake", "$14.50"], ["Black Forest Cake", "$45.00"], ["Mock Cream Vanilla Sponge Birthday Cake", "$45.00"], ["Chocolate Swiss Roll Cake", "$14.50"], ["Lemon Swiss Roll Cake", "$14.50"]]
        },
        {
            slug: "drinks",
            icon: "fa-bottle-water",
            image: "images/coffee 2.jpg",
            name: { en: "Drinks", vi: "Do uong" },
            intro: { en: "Cold drinks, iced tea, energy drinks, flavoured milk and bottled favourites.", vi: "Nuoc lanh, tra dao/chanh, nuoc tang luc, sua huong vi va do uong dong chai." },
            items: [["Canned Soft Drink", "$3.50"], ["Can Of Coke", "$3.50"], ["Red Fanta Bottle 600ml", "$6.80"], ["Can Of Coke No Sugar", "$3.50"], ["700ml Dare Iced Coffee", "$7.50"], ["Large Monster Can", "$6.50"], ["Bottle Of Coke No Sugar 600ml", "$6.80"], ["Peach / Lemon Iced Tea", "$6.50"], ["Soft Drink 600ml", "$6.80"], ["500ml Dare Iced Coffee / Chocolate Milk / Strawberry Milk", "$6.80"], ["Large V Can", "$7.80"], ["Bottle Of Coke 600ml", "$6.80"]]
        },
        {
            slug: "coffee",
            icon: "fa-mug-hot",
            image: "images/coffee 4.webp",
            name: { en: "Hot Coffee", vi: "Ca phe" },
            intro: { en: "Hot coffee, iced latte and Vietnamese iced coffee for the morning run.", vi: "Ca phe nong, iced latte va ca phe sua da cho buoi sang." },
            items: [["Latte", "$6.50"], ["Vietnamese Iced Coffee", "$7.90"], ["Cappuccino", "$6.50"], ["Flat White", "$6.50"], ["Iced Latte", "$7.50"], ["Long Black", "$6.50"]]
        }
    ],
    translations: {
        en: {
            "nav.homeAria": "Back home",
            "nav.menu": "Menu",
            "nav.about": "About",
            "nav.location": "Location",
            "nav.order": "Order",
            "nav.call": "Call",
            "nav.callAria": "Call Logan Reserve Bakehouse",
            "hero.badge": "Open 7 Days a Week",
            "hero.title": "The Bakehouse",
            "hero.titleAccent": "of Logan Reserve",
            "hero.copy": "From crispy Vietnamese banh mi to golden pies, pastries, cakes and hot coffee, Logan Reserve Bakehouse is the Logan Reserve stop for good food.",
            "hero.menuCta": "Explore Menu",
            "hero.orderCta": "Order Online",
            "updates.title": "Latest Updates",
            "updates.copy": "Synced with our facebook page.",
            "updates.follow": "Follow us",
            "updates.welcome": "Welcome to Logan Reserve Bakehouse",
            "updates.labour": "We are opened from 6am-6pm on Labour Day. See you then \ud83d\ude0d.",
            "updates.anzac": "We are opened from 6AM-6PM on Anzac day. Lest We Forget \u2764\ufe0f\ud83c\udde6\ud83c\uddfa",
            "updates.easter": "Easter Trading Hours. Happy Easter \ud83d\udc23",
            "menu.eyebrow": "Pick a category",
            "menu.title": "Menu",
            "menu.copy": "Plan, decide and order, starting with the 12 official Bakehouse categories below.",
            "menu.view": "View category",
            "menu.items": "items",
            "about.eyebrow": "About us",
            "about.title": "A neighbourhood bakery with Vietnamese heart.",
            "about.p1": "We make fresh banh mi, pies, pastries and bread daily \u2014 made for early mornings, lunch runs, and everything in between.",
            "about.p2": "We make fresh banh mi, pies, pastries and bread daily \u2014 made for early mornings, lunch runs, and everything in between.",
            "location.title": "Visit Us",
            "location.copy": "Find us in Logan Reserve Shopping Village with easy parking and fresh food ready every day.",
            "location.addressLabel": "Address",
            "location.hoursLabel": "Opening Hours",
            "location.weekdays": "Monday - Friday",
            "location.weekends": "Saturday - Sunday",
            "location.contactLabel": "Contact",
            "category.back": "Back to menu",
            "category.order": "Start an online order",
            "category.count": "Menu items",
            "order.eyebrow": "Online Order",
            "order.title": "Order ahead for pickup",
            "order.copy": "Use this form to prepare a regular pickup order or a larger catering request.",
            "order.back": "Back to home",
            "order.name": "Your name",
            "order.phone": "Phone number",
            "order.type": "Order type",
            "order.typeRegular": "Regular pickup",
            "order.typeCatering": "Bulk / catering",
            "order.item": "Item or request",
            "order.quantity": "Quantity",
            "order.pickup": "Pickup time",
            "order.date": "Pickup date",
            "order.notes": "Notes",
            "order.submit": "Submit order",
            "order.placeholder": "e.g. 4 roasted pork banh mi, no chilli",
            "order.notesPlaceholder": "Allergies, slicing, catering details or preferred pickup notes",
            "order.message": "Thanks. SMS ordering will be connected soon, so this demo form has not sent anything yet."
        },
        vi: {
            "nav.homeAria": "Ve trang chu Logan Reserve Bakehouse",
            "nav.menu": "Thuc don",
            "nav.about": "Gioi thieu",
            "nav.location": "Dia chi",
            "nav.order": "Dat mon",
            "nav.call": "Goi",
            "nav.callAria": "Goi Logan Reserve Bakehouse",
            "hero.badge": "Mo cua 7 ngay moi tuan",
            "hero.title": "Tiem banh",
            "hero.titleAccent": "cua Logan Reserve",
            "hero.copy": "Tu banh mi Viet Nam gion ngon den pie vang ruom, banh ngot, banh kem va ca phe nong, Logan Reserve Bakehouse la diem dung cua Logan Reserve cho mon an ngon.",
            "hero.menuCta": "Xem thuc don",
            "hero.orderCta": "Dat online",
            "updates.title": "Tin moi nhat",
            "updates.copy": "Dong bo voi trang Facebook cua chung toi.",
            "updates.follow": "Theo doi",
            "updates.welcome": "Chao mung den Logan Reserve Bakehouse",
            "updates.labour": "Chung toi mo cua tu 6am-6pm vao Labour Day. Hen gap ban \ud83d\ude0d.",
            "updates.anzac": "Chung toi mo cua tu 6AM-6PM vao Anzac day. Lest We Forget \u2764\ufe0f\ud83c\udde6\ud83c\uddfa",
            "updates.easter": "Gio mo cua dip Easter. Chuc mung Easter \ud83d\udc23",
            "menu.eyebrow": "Chon danh muc",
            "menu.title": "Thuc don",
            "menu.copy": "Len ke hoach, chon mon va dat hang, bat dau voi 12 danh muc chinh thuc cua Bakehouse ben duoi.",
            "menu.view": "Xem danh muc",
            "menu.items": "mon",
            "about.eyebrow": "Ve chung toi",
            "about.title": "Tiem banh dia phuong voi huong vi Viet Nam.",
            "about.p1": "Chung toi lam banh mi Viet Nam, pie, banh ngot va banh mi tuoi moi ngay \u2014 danh cho buoi sang som, bua trua nhanh va moi khoang thoi gian o giua.",
            "about.p2": "Chung toi lam banh mi Viet Nam, pie, banh ngot va banh mi tuoi moi ngay \u2014 danh cho buoi sang som, bua trua nhanh va moi khoang thoi gian o giua.",
            "location.title": "Ghe tham chung toi",
            "location.copy": "Tiem nam trong Logan Reserve Shopping Village, de dau xe va co do an tuoi moi ngay.",
            "location.addressLabel": "Dia chi",
            "location.hoursLabel": "Gio mo cua",
            "location.weekdays": "Thu Hai - Thu Sau",
            "location.weekends": "Thu Bay - Chu Nhat",
            "location.contactLabel": "Lien he",
            "category.back": "Ve thuc don",
            "category.order": "Dat truoc",
            "category.count": "So mon",
            "order.eyebrow": "Dat online",
            "order.title": "Dat mon truoc de den lay",
            "order.copy": "Dung mau nay cho don lay nhanh hoac don lon/catering. Hien tai mau chi la ban demo cho den khi ket noi SMS.",
            "order.back": "Ve trang chu",
            "order.name": "Ten cua ban",
            "order.phone": "So dien thoai",
            "order.type": "Loai don",
            "order.typeRegular": "Don thuong",
            "order.typeCatering": "Don lon / catering",
            "order.item": "Mon hoac yeu cau",
            "order.quantity": "So luong",
            "order.pickup": "Gio den lay",
            "order.date": "Ngay den lay",
            "order.notes": "Ghi chu",
            "order.submit": "Gui don",
            "order.placeholder": "VD: 4 banh mi heo quay, khong ot",
            "order.notesPlaceholder": "Di ung, cat banh, chi tiet catering hoac ghi chu pickup",
            "order.message": "Cam on. Chuc nang SMS se duoc ket noi sau, nen mau demo nay chua gui di."
        }
    }
};
